### ISSUE TITLE
DPT14 and 9 conversions do not return correct results

### ISSUE THREAD

**Issue by mwerski** [envy/libknxnet#1]
DPT14 (4byte float) is calculated the wrong way, for example "42 a5 5c 29" becomes something around 1100000000 instead of the correct "82.68".
As a workaround I have changed knxnet::data_to_4byte_float to:

```
float knxnet::data_to_4byte_float(uint8_t *data)
{
	uint32_t i=(data[1] << 24) | (data[2] << 16) | (data[3] << 8) | (data[4] << 0);
	return *(float*)&i;
}
```

Might not be the best solution but at least it returns the correct values.

**Comment by mwerski** [comment]
It is still not working as it should be. Values are ok for positive values but not for negative ones. Plz have a look at the following knx2influx log excerpt (a temperature reading, unfortunately I don't have raw values right now):

`temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.310000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.250000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.250000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.250000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.180000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.259979
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.259979
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.259979
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.259979
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.259979
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.259979
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.259979
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.259979
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.320007
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.320007
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.320007
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.320007
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-307.320007
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.000000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.060000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.120000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.180000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.180000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.180000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.310000
temp,sender=1.0.9,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=0.370000`

**Comment by envy** [comment]
Could you try to provide some raw values so I can test? Preferably one slightly above 0, one for 0 and one for slightly below zero? And maybe one for a bigger negative number. I sadly don't have a knx device that generates 4 byte floats.

**Comment by mwerski** [comment]
Yeah, sure. I have used the ETS to send DPT14.056 values to the bus with the following results:
`+81.22 -> 42 a2 70 a4

 +1.0 -> 3f 80 00 00

 +0.1 -> 3d cc cc cd

  0 -> 00 00 00 00

 -0.1 -> bd cc cc cd

 -1.0 -> bf 80 00 00

-81.22 -> c2 a2 70 a4`

Sending -10 leads to a raw data value of "c1 20 00 00" and to the following result in the knx2influx logfile:
`temp,sender=0.0.1,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-83148.796875`

**Comment by envy** [comment]
Thanks!

Unfortunately, the conversion itself seems to work for me. Here is a test program, can you compile and execute it on your machine please: https://gist.github.com/envy/aa08e0faf847f8c9621a8e4e6192c3b0

On my machine it prints:
```
+ 81.22: 81.220001
+  1.00: 1.000000
+  0.10: 0.100000
+  0.00: 0.000000
-  0.10: -0.100000
-  1.00: -1.000000
- 81.22: -81.220001
```

**Comment by mwerski** [comment]
Uhm... yes... sorry... I was somehow confused and ruffled my observations.
The test program is working fine and I suppose everything in libknxnet as well. What I have observed is actually another issue o\

The problem with negative values I described occurs when using DPT9 and not DPT14 (in other words: everything starting from my second comment is related to DPT9 and not DPT14 whereas the initial problem was actually DPT14 related and fixed).

Should I create some raw values for DPT9 as well?

**Comment by envy** [comment]
:D

Yes, some example values would be great

**Comment by mwerski** [comment]
Ok, same decimal values, sent via ETS as DPT9 (temperature), corresponding GA is configured as DPT9 in the knx2influx.json as well:

```
+81.2 :: 17 EE
+1.0  :: 00 64
+0.1  :: 00 0A
0     :: 00 00
-0.1  :: 87 F6
-1.0  :: 87 9C
-81.2 :: 90 12
-10   :: 84 18
```
with the last value creating the following log entry in knx2influx:
`temp,sender=0.0.1,room=EG-Technik,item=KWL(Frischluft-NachEWT),sensor=1wire value=-317.199982`

**Comment by envy** [comment]
Hi,

I just pushed a new version, could you test knx2influx with that new libknxnet?
The negative values near zero now work fine, the -81.2 is converted to -80.95, but that might be because of the low precision.

**Comment by mwerski** [comment]
I'd really love to do it, but unfortunately I don't have access to the (CentOS7) host I have used for testing anymore. I have setup an Ubuntu 16 LTS machine, but knx2influx refuses to compile on that setup o\

**Comment by mwerski** [comment]
The Ubuntu problem is apparently caused by a wrong order of the libraries to link against - I will open another issue for knx2influx regarding that issue.
I will test the new version as soon as possible and keep you informed about the results. Thx!

**Comment by mwerski** [comment]
Keeping the low precision in mind, the absolute value is correct for all testvalues I have tried (55.5, 11.1, 1.1, 0.1, 0, -0.1, -1.1, -11.1, -55.5) but unfortunately they are all unsigned - positive, to be more precise :)
